config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users
  get 'users/dashboard'

  resources :boats, only: %i[index show]

  resources :bets, only: %i[index new create]


  resources :crews, only: %i[index show new create] do
    resources :admissions, only: %i[create destroy]
    resources :races, only: %i[show]
  end

  patch "/admissions/:id/reject", to: "admissions#reject", as: "admission_reject"
  patch "/admissions/:id/accept", to: "admissions#accept", as: "admission_accept"
end

app/models/crew.rb
class Crew < ApplicationRecord
  belongs_to :user
  has_many :admissions, dependent: :destroy

  validates :name, presence: { message: "Le nom de la ligue est obligatoire" }
  validates :name, uniqueness: { message: "Malheureusement ce nom est déjà pris" }
  validates :name, length: { in: 3..15 , message: "Le nom de la ligue doit être compris entre 3 et 30 caractères"}

  has_one_attached :logo

  def number_of_members
    self.admissions.where(status: "accepted").count + 1
  end

  def self.includes_user(user)
    crews = Crew.where(user: user)
    crews_requested = Crew.includes(:admissions).where(admissions: {user: user, status: "accepted"})
    crews + crews_requested
  end

  def not_contains_user?(user)
    self.user != user && self.admissions.where(user: user).empty?
  end

  def validation_done_for?(user)
    !self.admissions.where(status: "accepted", user: user).empty?
  end

  def waiting_to_access?(user)
    !self.admissions.where(status: "pending", user: user).empty? && self.user != user
  end
end

app/controllers/crews_controller.rb
class CrewsController < ApplicationController
  def index
    @crews = Crew.all
    @admission = Admission.new
  end

  def show
  end

  def new
    @crew = Crew.new
  end

  def create
    @crew = Crew.new(crew_params)
    @crew.user = current_user
    if @crew.save
      redirect_to crew_race_path(@crew, Race.last)
    else
      flash[:notice] = @crew.errors.first.message
      redirect_to new_crew_path
    end
  end

  private

  def crew_params
    params.require(:crew).permit(:name, :logo)
  end
end

app/helpers/crews_helper.rb
module CrewsHelper
end

app/views/crews/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Crews#create</h1>
  <p>Find me in app/views/crews/create.html.erb</p>
</div>

app/views/crews/index.html.erb
<div class="crew-bcg">

  <div class="text-center mb-4">
    <%= link_to "Créer une ligue", new_crew_path, class: "btn-main" %>
  </div>

  <div class="crew-cards">
    <% @crews.each do |crew| %>
      <div class="crew-card">
        <div class="flex justify-around items-center">
          <%= cl_image_tag crew.logo.key, class: "logo" %>
          <div>
            <h2><%= crew.name %></h2>
            <p>créé par <%= crew.user.username %></p>
            <p><i class="fa-solid fa-people-group"></i> <%= crew.number_of_members %></p>
          </div>
        </div>
        <div>
          <% if crew.validation_done_for?(current_user)%>
            <%= link_to "Quitter", crew_admissions_path(crew, crew.admissions.where(user: current_user).first), class: "btn-quit", method: :delete %>
          <% elsif crew.waiting_to_access?(current_user) %>
            <p><em>En attente</em></p>
          <% elsif crew.not_contains_user?(current_user) %>
            <%= simple_form_for [crew, @admission] do |f| %>
              <%= f.submit "Rejoindre", class: "btn-join" %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/crews/new.html.erb
<div class="crew-bcg">
  <h1 class='text-center my-4'>Je crée ma ligue</h1>

  <div class="form-crew">
    <%= simple_form_for @crew do |f| %>
        <div class="form-input"><%= f.input :name, label: false, placeholder: "Le nom de ma ligue" %></div>
        <div class="form-input-logo"><%= f.input :logo, label: false, placeholder: "Le logo de ta ligue", as: :file %></div>
        <div class="form-button"><%= f.submit "Créer ma ligue !", class: "btn-bet" %></div>
    <% end %>
  </div>
</div>

app/views/crews/show.html.erb
<div>
  <h1 class="font-bold text-4xl">Crews#show</h1>
  <p>Find me in app/views/crews/show.html.erb</p>
</div>