config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users
  get 'users/dashboard'

  resources :boats, only: %i[index show]

  resources :bets, only: %i[index new create]


  resources :crews, only: %i[index show new create] do
    resources :admissions, only: %i[create destroy]
    resources :races, only: %i[show]
  end

  patch "/admissions/:id/reject", to: "admissions#reject", as: "admission_reject"
  patch "/admissions/:id/accept", to: "admissions#accept", as: "admission_accept"
end

app/models/user.rb
require "open-uri"

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bets, dependent: :destroy
  has_many :crews, dependent: :destroy
  has_many :admissions, dependent: :destroy
  has_many :scores, dependent: :destroy
  has_many :total_scores, dependent: :destroy

  validates :first_name, :last_name, :username, presence: true
  validates :email, uniqueness: true

  has_one_attached :avatar
  before_create :assign_avatar
  after_create :score_initialization, :total_score_initialization

  def self.accepted_in_league(crew, race, category = nil)
    owner = User.joins(:total_scores, :scores).includes(:crews).where(crews: { id: crew.id })
    accepted_users = User.joins(:total_scores, :scores).includes(:admissions).where(admissions: { crew: crew, status: "accepted" })
    players = owner + accepted_users
    if category
      return players.sort_by { |player| player.scores.where(race: race).first.points_by_category[category] }
    else
      return players.sort_by { |player| player.total_scores.where(race: race).first.points }
    end
  end

  private
  def assign_avatar
    return if avatar.attached?

    photoavatar = URI.open('https://res.cloudinary.com/dciokrtia/image/upload/v1698344511/development/6rvjnlu98a6o65w5q6w1qqzzqzii.jpg')
    avatar.attach(io: photoavatar, filename: 'avatar.png', content_type: 'image/png')
  end

  def score_initialization
    score = Score.new(
      race: Race.last,
      user: self,
    )
    categories = Race.last.categories
    score.points_by_category = categories.map { |category| [category['name'], 0]}.to_h
    score.save!
  end

  def total_score_initialization
    TotalScore.create!(
      race: Race.last,
      user: self,
      points: 0
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @my_crews = Crew.includes_user(current_user)
    @requests = Admission.waiting_validation(current_user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/dashboard.html.erb
<div class="dashboard-bcg">
  <div>
    <h1>Mes ligues (<%= @my_crews.count %>)</h1>
    <div>
      <% if @my_crews.empty? %>
        <p class="text-center m-3"><%= link_to "Voir les ligues", crews_path, class: "btn-main" %></p>
      <% else %>
        <div class="crew-cards">
          <% @my_crews.each do |crew| %>
            <div class="crew-img-dsb">
              <%= link_to crew_race_path(crew, Race.last) do %>
                <%= cl_image_tag crew.logo.key, alt: "text", class: "" %>
                <h2 class="crew-img-dsb-txt"><%= crew.name %></h2>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class>
    <h1>Demandes d'adhésion à mes ligues (<%= @requests.count %>)</h1>
    <div class="admission-cards">
      <% unless @requests.empty? %>
        <% @requests.each do |request| %>
          <div class="admission-card">
            <div>
              <%= cl_image_tag request.crew.logo.key, class: "logo" %>
              <h2><%= request.crew.name %></h2>
            </div>
            <div class="admission-user">
              <%= cl_image_tag request.user.avatar.key, class: "avatar" %>
              <p><%= request.user.first_name %> <%= request.user.last_name %></p>
              <p><em>alias</em> <%= request.user.username %></p>
            </div>
            <div class="admission-validation">
              <div class="admission-ok">
                <%= link_to admission_accept_path(request), data: {turbo_method: :patch}, class: "btn-accept" do %>
                  <i class="fas fa-check-circle"></i>
                <% end %>
              </div>
              <div class="admission-ko">
                <%= link_to admission_reject_path(request), data: {turbo_method: :patch}, class: "btn-quit" do %>
                  <i class="fas fa-times-circle"></i>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>