config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users
  get 'users/dashboard'

  resources :boats, only: %i[index show]

  resources :bets, only: %i[index new create]


  resources :crews, only: %i[index show new create] do
    resources :admissions, only: %i[create destroy]
    resources :races, only: %i[show]
  end

  patch "/admissions/:id/reject", to: "admissions#reject", as: "admission_reject"
  patch "/admissions/:id/accept", to: "admissions#accept", as: "admission_accept"
end

app/views/shared/_bets_card.html.erb
<% if bets.empty? %>
  <div class='flex justify-around items-center'>
    <% unless Time.zone.now > starting_time %>
      <%= link_to "Je fais mes paris en #{category}", new_bet_path(category: category), class: 'btn-main' %>
   <% end %>
  </div>
<% else %>
  <div class='bet-card'>
    <% bets.each do |bet| %>
      <div>
        <p class='bet-card-text'><%= bet.position %> - <%= bet.boat.name %></p>
      </div>
    <% end %>
    <% unless Time.zone.now > starting_time %>
      <%= link_to "Je modifie mes paris en #{category}", new_bet_path(category: category), class: 'text-change' %>
    <% end %>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="bg-yellow-100 border border-yellow-400 text-yellow-700 px-4 py-3 rounded relative" role="alert" data-controller="close-button" data-close-button-target="info">
    <%= notice %>
    <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
      <svg class="fill-current h-6 w-6 text-yellow-500" role="button" xmlns="http://www.w3.org/2000/svg" data-action="click->close-button#close" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
    </span>
  </div>
<% end %>
<% if alert %>
  <div class="bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded relative" role="alert" data-controller="close-button" data-close-button-target="info">
    <%= alert %>
    <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
      <svg class="fill-current h-6 w-6 text-blue-500" role="button" xmlns="http://www.w3.org/2000/svg" data-action="click->close-button#close" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
    </span>
  </div>
<% end %>

app/views/shared/_form_bets.html.erb
<%= form_with url: bets_path(category: params[:category]), method: :post do |f| %>
  <div class="my-3">
    <%= f.select :first_boat, Boat.get_all_by_category(params[:category]), prompt: 'Vainqueur' %>
  </div>
  <div class="my-3">
    <%= f.select :second_boat, Boat.get_all_by_category(params[:category]), prompt: 'Deuxième' %>
  </div>
  <div class="my-3">
    <%= f.select :third_boat, Boat.get_all_by_category(params[:category]), prompt: 'Troisième' %>
  </div>
  <div class="my-3 form-button">
    <%= f.submit "Bon vent !", class: "btn-bet" %>
  </div>
<% end %>

app/views/shared/_navbar_top.html.erb
<div class="navbar-top">
  <div>
    <h3><%= link_to "Accueil", root_path %></h3>
  </div>
  <% if user_signed_in? %>
    <div class="flex">
      <h3><%= link_to "Engagés", boats_path %></h3>
      <h3><%= link_to "Paris", bets_path %></h3>
      <h3><%= link_to "Ligues", crews_path %></h3>
    </div>
    <div class="flex">
      <h3><%= link_to "Compte", users_dashboard_path %></h3>
      <%= link_to destroy_user_session_path, data: {turbo_method: :delete} do %>
        <i class="fa-solid fa-arrow-right-from-bracket"></i>
      <% end %>
    </div>
  <% else %>
    <div>
      <h3><%= link_to "Se connecter", new_user_session_path %></h3>
      <h3><%= link_to "S'inscrire", new_user_registration_path %></h3>
    </div>
  <% end %>



</div>